/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.appointments;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.tecno_comfenalco.easywashproject.controllers.AuthController;
import com.tecno_comfenalco.easywashproject.models.Appointment;
import com.tecno_comfenalco.easywashproject.models.Client;
import com.tecno_comfenalco.easywashproject.models.Service;
import com.tecno_comfenalco.easywashproject.repository.FileBasedRepsitoryImpl.AppointmentRepositoryImpl;
import com.tecno_comfenalco.easywashproject.repository.FileBasedRepsitoryImpl.ClientRepositoryImpl;

/**
 *
 * @author jacob
 */
public class VerCitasPanel extends javax.swing.JPanel {
    private final AuthController authController = AuthController.getInstance();

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form VerCitasPanel1
     */
    public VerCitasPanel() {
        initComponents();
        String[] titulo = new String[] { "Tipo de servicio", "Precio", "Trabajador", "Estado", "Fecha", "Hora" };
        dtm.setColumnIdentifiers(titulo);

        Client client = new ClientRepositoryImpl().findByDocumentNumber(authController.getSession());

        if (client == null) {
            JOptionPane.showMessageDialog(null, "No se encontró ninguna sesión coincidente", "Error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

        AppointmentRepositoryImpl repo = new AppointmentRepositoryImpl();
        List<Appointment> appointments = repo.readAll();

        if (client != null) {
            // Si hay un cliente, filtra las citas por el cliente activo en la sesión
            for (Appointment appointment : appointments) {
                if (appointment.getClient() == null || appointment.getService() == null
                        || appointment.getEmployee() == null)
                    continue;

                if (appointment.getClient().getDocumentNumber().equals(client.getDocumentNumber())) {
                    for (Service service : appointment.getService()) {
                        dtm.addRow(new Object[] {
                                service.getName(), service.getPrice(), appointment.getEmployee().getFullname(),
                                appointment.getStatus(), appointment.getDate(), appointment.getStartTime().toString()
                        });
                    }
                }
            }
        }

        jTable1.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setText("Ver Citas");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "Tipo de Servicio", "Precio", "Trabajador", "Estado", "Fecha", "Hora"
                }));
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 600, 320));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
