/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.admin;

import com.tecno_comfenalco.easywashproject.views.appointments.VerCitasAdministradorPanel;
import com.tecno_comfenalco.easywashproject.views.appointments.VerHistorialAdministradorPanel;
import com.tecno_comfenalco.easywashproject.views.services.VerServiciosAdministradorPanel;
import com.tecno_comfenalco.easywashproject.views.employees.VerTrabajadoresAdministradorPanel;
import java.awt.BorderLayout;

/**
 *
 * @author jacob
 */
public class DashBoardUserView extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardUserView
     */
    public DashBoardUserView() {
        initComponents();
        
        VerCitasAdministradorPanel p4 = new VerCitasAdministradorPanel();
        p4.setSize(630, 400);
        p4.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p4, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextTitulo = new javax.swing.JLabel();
        VerCitas = new javax.swing.JButton();
        VerHistorial = new javax.swing.JButton();
        VerServicios = new javax.swing.JButton();
        VerTrabajadores = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        TextTitulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextTitulo.setText("¡Bienvenido al sistema, usuario!");
        bg.add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        VerCitas.setBackground(new java.awt.Color(153, 204, 255));
        VerCitas.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerCitas.setText("Ver Citas");
        VerCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCitasActionPerformed(evt);
            }
        });
        bg.add(VerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 120, 40));

        VerHistorial.setBackground(new java.awt.Color(255, 255, 153));
        VerHistorial.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerHistorial.setText("Ver Historial");
        VerHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerHistorialActionPerformed(evt);
            }
        });
        bg.add(VerHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 120, 40));

        VerServicios.setBackground(new java.awt.Color(102, 255, 102));
        VerServicios.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerServicios.setText("Ver Servicios");
        VerServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerServiciosActionPerformed(evt);
            }
        });
        bg.add(VerServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 120, 40));

        VerTrabajadores.setBackground(new java.awt.Color(0, 102, 102));
        VerTrabajadores.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerTrabajadores.setText("Ver Trabajadores");
        VerTrabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTrabajadoresActionPerformed(evt);
            }
        });
        bg.add(VerTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 120, 40));

        Salir.setBackground(new java.awt.Color(255, 0, 51));
        Salir.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 120, 40));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        bg.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 400));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerServiciosActionPerformed
        VerServiciosAdministradorPanel p6 = new VerServiciosAdministradorPanel();
        p6.setSize(630, 400);
        p6.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p6, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerServiciosActionPerformed

    private void VerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCitasActionPerformed
        VerCitasAdministradorPanel p4 = new VerCitasAdministradorPanel();
        p4.setSize(630, 400);
        p4.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p4, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerCitasActionPerformed

    private void VerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerHistorialActionPerformed
        VerHistorialAdministradorPanel p5 = new VerHistorialAdministradorPanel();
        p5.setSize(630, 400);
        p5.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p5, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerHistorialActionPerformed

    private void VerTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTrabajadoresActionPerformed
        VerTrabajadoresAdministradorPanel p7 = new VerTrabajadoresAdministradorPanel();
        p7.setSize(630, 400);
        p7.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p7, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerTrabajadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel TextTitulo;
    private javax.swing.JButton VerCitas;
    private javax.swing.JButton VerHistorial;
    private javax.swing.JButton VerServicios;
    private javax.swing.JButton VerTrabajadores;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
