/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.admin;

import com.tecno_comfenalco.easywashproject.controllers.NavigationManager;
import com.tecno_comfenalco.easywashproject.views.appointments.VerCitasAdministradorPanel;
import com.tecno_comfenalco.easywashproject.views.appointments.VerHistorialAdministradorPanel;
import com.tecno_comfenalco.easywashproject.views.appointments.VerHistorialPanel;
import com.tecno_comfenalco.easywashproject.views.employees.VerTrabajadoresAdministradorPanel;
import com.tecno_comfenalco.easywashproject.views.services.VerServiciosAdministradorPanel;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument.Content;

/**
 *
 * @author jacob
 */
public class DashboardUserView extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardUserView1
     */
    public DashboardUserView() {
        initComponents();
        
        VerCitasAdministradorPanel p4 = new VerCitasAdministradorPanel();
        p4.setSize(630, 400);
        p4.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p4, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TextTitulo = new javax.swing.JLabel();
        VerCitas = new javax.swing.JButton();
        VerHistorial = new javax.swing.JButton();
        VerServicios = new javax.swing.JButton();
        VerTrabajadores = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        TextTitulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextTitulo.setText("¡Bienvenido al Sistema, usuario!");
        bg.add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        VerCitas.setBackground(new java.awt.Color(153, 204, 255));
        VerCitas.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerCitas.setText("Ver Citas");
        VerCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCitasActionPerformed(evt);
            }
        });
        bg.add(VerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 120, 40));

        VerHistorial.setBackground(new java.awt.Color(255, 255, 204));
        VerHistorial.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerHistorial.setText("Ver Historial");
        VerHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerHistorialActionPerformed(evt);
            }
        });
        bg.add(VerHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 120, 40));

        VerServicios.setBackground(new java.awt.Color(102, 255, 102));
        VerServicios.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerServicios.setText("Ver Servicios");
        VerServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerServiciosActionPerformed(evt);
            }
        });
        bg.add(VerServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 120, 40));

        VerTrabajadores.setBackground(new java.awt.Color(204, 204, 204));
        VerTrabajadores.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerTrabajadores.setText("Ver Trabajadores");
        VerTrabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTrabajadoresActionPerformed(evt);
            }
        });
        bg.add(VerTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 120, 40));

        Salir.setBackground(new java.awt.Color(255, 0, 51));
        Salir.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        bg.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 120, 40));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        bg.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 640, 400));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void VerServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerServiciosActionPerformed
        VerServiciosAdministradorPanel p6 = new VerServiciosAdministradorPanel();
        p6.setSize(630, 400);
        p6.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p6, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerServiciosActionPerformed

    private void VerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCitasActionPerformed
        VerCitasAdministradorPanel p4 = new VerCitasAdministradorPanel();
        p4.setSize(630, 400);
        p4.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p4, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerCitasActionPerformed

    private void VerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerHistorialActionPerformed

        VerHistorialPanel p2 = new VerHistorialPanel();
        p2.setSize(630, 400);
        p2.setLocation(0, 0);

        Content.removeAll();
        Content.add(p2, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerHistorialActionPerformed

    private void VerTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTrabajadoresActionPerformed
        VerTrabajadoresAdministradorPanel p7 = new VerTrabajadoresAdministradorPanel();
        p7.setSize(630, 400);
        p7.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p7, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerTrabajadoresActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Estas seguro que desea salir?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            this.dispose();
            NavigationManager.showMainView();
        }
    }//GEN-LAST:event_SalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUserView().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel TextTitulo;
    private javax.swing.JButton VerCitas;
    private javax.swing.JButton VerHistorial;
    private javax.swing.JButton VerServicios;
    private javax.swing.JButton VerTrabajadores;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
