/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.Dashboard.Admin;

import com.tecno_comfenalco.easywashproject.views.Dashboard.Admin.panels.AppointmentListPanel;
import com.tecno_comfenalco.easywashproject.views.Dashboard.Admin.panels.EmployeeListPanel;
import com.tecno_comfenalco.easywashproject.views.Dashboard.Admin.panels.HistoryAppointmentList;
import com.tecno_comfenalco.easywashproject.views.Dashboard.Admin.panels.ServicesListPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author danil
 */
public class DashboardAdminView extends javax.swing.JFrame {

    public final static String VISTA_CITAS = "VISTA_CITAS";
    public final static String VISTA_EMPLEADOS = "VISTA_EMPLEADOS";
    public final static String VISTA_SERVICIOS = "VISTA_SERVICIOS";
    public final static String VISTA_HISTORIAL = "VISTA_HISTORIAL";

    AppointmentListPanel listaCitasPanel = new AppointmentListPanel();
    EmployeeListPanel listaEmpleadosPanel = new EmployeeListPanel();
    ServicesListPanel listaServiciosPanel = new ServicesListPanel();
    HistoryAppointmentList historialCitasPanel = new HistoryAppointmentList();
    
    InitialContentPanel contenidoInicialPanel;

    public DashboardAdminView() {
        initComponents();

        contenidoInicialPanel = new InitialContentPanel();
        DashboardMainLayoutPanel.setLayout(new CardLayout(0, 0));

        DashboardMainLayoutPanel.add(listaCitasPanel, VISTA_CITAS);
        DashboardMainLayoutPanel.add(listaEmpleadosPanel, VISTA_EMPLEADOS);
        DashboardMainLayoutPanel.add(listaServiciosPanel, VISTA_SERVICIOS);
        DashboardMainLayoutPanel.add(historialCitasPanel, VISTA_HISTORIAL);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DashboardSidebarMenu = new javax.swing.JPanel();
        ViewAppointmentsBtn = new javax.swing.JLabel();
        ViewHistoryBtn = new javax.swing.JLabel();
        ViewServicesBtn = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JLabel();
        ViewEmployeesBtn = new javax.swing.JLabel();
        DashboardMainLayoutPanel = new javax.swing.JPanel();
        initialContentPanel1 = new com.tecno_comfenalco.easywashproject.views.Dashboard.Admin.InitialContentPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashboardSidebarMenu.setBackground(new java.awt.Color(204, 204, 204));

        ViewAppointmentsBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\danil\\OneDrive\\Documents\\NetBeansProjects\\EasyWashProject\\src\\main\\java\\com\\tecno_comfenalco\\easywashproject\\public\\view_appointments_btn.png")); // NOI18N
        ViewAppointmentsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAppointmentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAppointmentsBtnMouseClicked(evt);
            }
        });

        ViewHistoryBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\danil\\OneDrive\\Documents\\NetBeansProjects\\EasyWashProject\\src\\main\\java\\com\\tecno_comfenalco\\easywashproject\\public\\view_history_btn.png")); // NOI18N
        ViewHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewHistoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewHistoryBtnMouseClicked(evt);
            }
        });

        ViewServicesBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\danil\\OneDrive\\Documents\\NetBeansProjects\\EasyWashProject\\src\\main\\java\\com\\tecno_comfenalco\\easywashproject\\public\\view_services_btn.png")); // NOI18N
        ViewServicesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewServicesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewServicesBtnMouseClicked(evt);
            }
        });

        ExitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\danil\\OneDrive\\Documents\\NetBeansProjects\\EasyWashProject\\src\\main\\java\\com\\tecno_comfenalco\\easywashproject\\public\\dashboard_exit_btn.png")); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });

        ViewEmployeesBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\danil\\OneDrive\\Documents\\NetBeansProjects\\EasyWashProject\\src\\main\\java\\com\\tecno_comfenalco\\easywashproject\\public\\view_employees_btn.png")); // NOI18N
        ViewEmployeesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewEmployeesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewEmployeesBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DashboardSidebarMenuLayout = new javax.swing.GroupLayout(DashboardSidebarMenu);
        DashboardSidebarMenu.setLayout(DashboardSidebarMenuLayout);
        DashboardSidebarMenuLayout.setHorizontalGroup(
            DashboardSidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardSidebarMenuLayout.createSequentialGroup()
                .addGroup(DashboardSidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardSidebarMenuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ViewAppointmentsBtn))
                    .addGroup(DashboardSidebarMenuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(DashboardSidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewHistoryBtn)
                            .addComponent(ViewServicesBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardSidebarMenuLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(DashboardSidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardSidebarMenuLayout.createSequentialGroup()
                        .addComponent(ViewEmployeesBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardSidebarMenuLayout.createSequentialGroup()
                        .addComponent(ExitBtn)
                        .addGap(54, 54, 54))))
        );
        DashboardSidebarMenuLayout.setVerticalGroup(
            DashboardSidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardSidebarMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ViewAppointmentsBtn)
                .addGap(18, 18, 18)
                .addComponent(ViewHistoryBtn)
                .addGap(30, 30, 30)
                .addComponent(ViewServicesBtn)
                .addGap(18, 18, 18)
                .addComponent(ViewEmployeesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitBtn)
                .addGap(65, 65, 65))
        );

        DashboardMainLayoutPanel.setMinimumSize(new java.awt.Dimension(1370, 1000));
        DashboardMainLayoutPanel.setLayout(new java.awt.CardLayout());

        initialContentPanel1.setBackground(new java.awt.Color(255, 255, 255));
        initialContentPanel1.setForeground(new java.awt.Color(0, 0, 0));
        DashboardMainLayoutPanel.add(initialContentPanel1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(DashboardMainLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DashboardSidebarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardSidebarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DashboardMainLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );

        DashboardMainLayoutPanel.add(listaCitasPanel);
        DashboardMainLayoutPanel.add(listaEmpleadosPanel);
        DashboardMainLayoutPanel.add(listaServiciosPanel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAppointmentsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAppointmentsBtnMouseClicked
        CardLayout c1 = (CardLayout) (DashboardMainLayoutPanel.getLayout());
        c1.show(DashboardMainLayoutPanel, VISTA_CITAS);
    }//GEN-LAST:event_ViewAppointmentsBtnMouseClicked

    private void ViewHistoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewHistoryBtnMouseClicked
        CardLayout c1 = (CardLayout) (DashboardMainLayoutPanel.getLayout());
        c1.show(DashboardMainLayoutPanel, VISTA_HISTORIAL);
    }//GEN-LAST:event_ViewHistoryBtnMouseClicked

    private void ViewEmployeesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewEmployeesBtnMouseClicked
        CardLayout c1 = (CardLayout) (DashboardMainLayoutPanel.getLayout());
        c1.show(DashboardMainLayoutPanel, VISTA_EMPLEADOS);
    }//GEN-LAST:event_ViewEmployeesBtnMouseClicked

    private void ViewServicesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewServicesBtnMouseClicked
        CardLayout c1 = (CardLayout) (DashboardMainLayoutPanel.getLayout());
        c1.show(DashboardMainLayoutPanel, VISTA_SERVICIOS);
    }//GEN-LAST:event_ViewServicesBtnMouseClicked

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashboardMainLayoutPanel;
    private javax.swing.JPanel DashboardSidebarMenu;
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel ViewAppointmentsBtn;
    private javax.swing.JLabel ViewEmployeesBtn;
    private javax.swing.JLabel ViewHistoryBtn;
    private javax.swing.JLabel ViewServicesBtn;
    private com.tecno_comfenalco.easywashproject.views.Dashboard.Admin.InitialContentPanel initialContentPanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
