/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views;

/**
 *
 * @author jacob
 */
public class MainClientView extends javax.swing.JFrame {

    /**
     * Creates new form MainClientView
     */
    public MainClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TextTitulo = new javax.swing.JLabel();
        TextRegistrado = new javax.swing.JLabel();
        TextNoregistrado = new javax.swing.JLabel();
        BotonAfirmacion = new javax.swing.JButton();
        BotonNegacion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        TextMedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 760, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        TextTitulo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        TextTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTitulo.setText("¡Hola! Bienvenido al Sistema de Gestion de Citas para Autolavado");
        getContentPane().add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 93, -1, -1));

        TextRegistrado.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextRegistrado.setText("¿Estas Registrado?");
        getContentPane().add(TextRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 190, -1, -1));

        TextNoregistrado.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextNoregistrado.setText("¿No Estas Registrado?");
        getContentPane().add(TextNoregistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 190, -1, -1));

        BotonAfirmacion.setBackground(new java.awt.Color(102, 255, 51));
        BotonAfirmacion.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonAfirmacion.setText("Tengo Cuenta");
        BotonAfirmacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BotonAfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 299, 156, 46));

        BotonNegacion.setBackground(new java.awt.Color(255, 204, 0));
        BotonNegacion.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonNegacion.setText("No Tengo Cuenta");
        BotonNegacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BotonNegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 299, -1, 46));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 220, -1, 50));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 220, -1, 50));

        TextMedio.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextMedio.setText("O");
        getContentPane().add(TextMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 308, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAfirmacion;
    private javax.swing.JButton BotonNegacion;
    private javax.swing.JLabel TextMedio;
    private javax.swing.JLabel TextNoregistrado;
    private javax.swing.JLabel TextRegistrado;
    private javax.swing.JLabel TextTitulo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
