/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views;

import com.tecno_comfenalco.easywashproject.enums.EnumDocType;
import com.tecno_comfenalco.easywashproject.models.Client;
import com.tecno_comfenalco.easywashproject.repository.FileBasedRepsitoryImpl.ClientRepositoryImpl;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jacob
 */
public class RegisterClientView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterClientView
     */
    public RegisterClientView() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //No cierra toda la app
        loadDocumentTypes();
    }
    
   
    public String getNombre() {
        return NombreSave.getText().trim();
    }
    
    public String getTipoDocumento() {
        return jComboBox1.getSelectedItem().toString();
    }
    
    public String getDocumento() {
        return DocumentoSave.getText().trim();
    }
    
    public String getTelefono() {
        return NumberPhoneSave.getText().trim();
    }
    
    public String getCorreo() {
        return CorreoSave.getText().trim();
    }
    
    public void setRegisterListener(ActionListener listener) {
        btnRegistrar.addActionListener(listener);
    }
    
    public void setCancelListener(ActionListener listener) {
        btnCancelar.addActionListener(listener);
    }
    
    public void showError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showSuccess(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Exito", JOptionPane.INFORMATION_MESSAGE);
    }
    
     private void loadDocumentTypes() {
        jComboBox1.removeAllItems();
        for (String desc : EnumDocType.getDescripciones()){
            jComboBox1.addItem(desc);
        }
    }
    
    
    private void limpiarCampos() {
        NombreSave.setText("");
        jComboBox1.setSelectedIndex(0);
        DocumentoSave.setText("");
        NumberPhoneSave.setText("");
        CorreoSave.setText("");   
    }
    public void close(){
        this.dispose();
    }
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PrimerParametro = new javax.swing.JLabel();
        SegundoParametro = new javax.swing.JLabel();
        NombreSave = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        TercerParametro = new javax.swing.JLabel();
        CuartoParametro = new javax.swing.JLabel();
        DocumentoSave = new javax.swing.JTextField();
        NumberPhoneSave = new javax.swing.JTextField();
        QuintoParametro = new javax.swing.JLabel();
        CorreoSave = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Registro de Nuevo Cliente");
        bg.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        BarraSuperior.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 759, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        PrimerParametro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        PrimerParametro.setText("Nombre Completo");
        bg.add(PrimerParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        SegundoParametro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        SegundoParametro.setText("Tipo de Documento");
        bg.add(SegundoParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        NombreSave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreSave.setText("Ingrese nombre completo");
        NombreSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreSaveActionPerformed(evt);
            }
        });
        bg.add(NombreSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 240, 40));

        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 230, 40));

        TercerParametro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        TercerParametro.setText("Numero de Documento");
        bg.add(TercerParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        CuartoParametro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        CuartoParametro.setText("Numero de Telefono");
        bg.add(CuartoParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        DocumentoSave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DocumentoSave.setText("Ingrese su numero de documento");
        DocumentoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentoSaveActionPerformed(evt);
            }
        });
        bg.add(DocumentoSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 240, 40));

        NumberPhoneSave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NumberPhoneSave.setText("Ingrese su numero de telefono");
        NumberPhoneSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberPhoneSaveActionPerformed(evt);
            }
        });
        bg.add(NumberPhoneSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 230, 40));

        QuintoParametro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        QuintoParametro.setText("Correo");
        bg.add(QuintoParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        CorreoSave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CorreoSave.setText("Ingrese su correo");
        CorreoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoSaveActionPerformed(evt);
            }
        });
        bg.add(CorreoSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 240, 40));

        btnRegistrar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 373, 170, 50));

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 433, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void DocumentoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentoSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentoSaveActionPerformed

    private void NumberPhoneSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberPhoneSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberPhoneSaveActionPerformed

    private void CorreoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoSaveActionPerformed

    private void NombreSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreSaveActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Metodo para registrar nuevo cliente 
        try {
            String nombreCompleto = NombreSave.getText();
            String tipoDocumento = (String) jComboBox1.getSelectedItem();
            String numeroDocumento = DocumentoSave.getText();
            String numeroTelefono = NumberPhoneSave.getText();
            String correo = CorreoSave.getText();
            
            if (nombreCompleto.isEmpty() || numeroDocumento.isEmpty() || numeroTelefono.isEmpty() || correo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            EnumDocType docType;
            try {
                docType = EnumDocType.valueOf(tipoDocumento);
            }catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "Tipo de documento no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            Client client = new Client (null, nombreCompleto, docType, numeroDocumento, numeroTelefono, correo);
            
            try {
                ClientRepositoryImpl clientRepositoryImpl = new ClientRepositoryImpl();
                clientRepositoryImpl.create(client);
                               JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                               limpiarCampos();
                               System.out.println("Cliente registrado: " + client);
            
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar el cliente" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch (Exception e) {
           System.out.println("Error al registrar al cliente: " + e.getMessage());
           JOptionPane.showMessageDialog(this, "Error al registrar al cliente", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JTextField CorreoSave;
    private javax.swing.JLabel CuartoParametro;
    private javax.swing.JTextField DocumentoSave;
    private javax.swing.JTextField NombreSave;
    private javax.swing.JTextField NumberPhoneSave;
    private javax.swing.JLabel PrimerParametro;
    private javax.swing.JLabel QuintoParametro;
    private javax.swing.JLabel SegundoParametro;
    private javax.swing.JLabel TercerParametro;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
