/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views;

import com.tecno_comfenalco.easywashproject.controllers.NavigationManager;
import javax.swing.JFrame;

/**
 *
 * @author jacob
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setupListeners();
        setSize(800,500);
    }
    
    private void setupListeners() {
        BotonAdministrador.addActionListener(e -> {
            this.dispose();
            NavigationManager.showLoginUserView();
        });
        
        BotonCliente.addActionListener(e -> {
            this.dispose();
            NavigationManager.showMainView();
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TextTitulo = new javax.swing.JLabel();
        TextPregunta = new javax.swing.JLabel();
        TextAdministrador = new javax.swing.JLabel();
        TextCliente = new javax.swing.JLabel();
        BotonAdministrador = new javax.swing.JButton();
        BotonCliente = new javax.swing.JButton();
        TextMitad = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(884, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        TextTitulo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        TextTitulo.setText("¡Hola! Bienvenido al Sistema de Gestion de Citas  EasyWash");
        getContentPane().add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 660, 60));

        TextPregunta.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextPregunta.setText("¿Quien eres?");
        getContentPane().add(TextPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        TextAdministrador.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextAdministrador.setText("¿Un Administrador?");
        getContentPane().add(TextAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        TextCliente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextCliente.setText("¿Un Cliente?");
        getContentPane().add(TextCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        BotonAdministrador.setBackground(new java.awt.Color(255, 204, 0));
        BotonAdministrador.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonAdministrador.setText("Soy un Administrador");
        BotonAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAdministradorMouseClicked(evt);
            }
        });
        getContentPane().add(BotonAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 46));

        BotonCliente.setBackground(new java.awt.Color(102, 255, 51));
        BotonCliente.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonCliente.setText("Soy un Cliente");
        BotonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonClienteMouseClicked(evt);
            }
        });
        getContentPane().add(BotonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 156, 46));

        TextMitad.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        TextMitad.setText("O");
        getContentPane().add(TextMitad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAdministradorMouseClicked
        this.dispose();
        LoginUserView adminLogin = new LoginUserView();
        adminLogin.setVisible(true);
    }//GEN-LAST:event_BotonAdministradorMouseClicked

    private void BotonClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClienteMouseClicked
        this.dispose();
        MainClientView clientView = new MainClientView();
        clientView.setVisible(true);
        
    }//GEN-LAST:event_BotonClienteMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAdministrador;
    private javax.swing.JButton BotonCliente;
    private javax.swing.JLabel TextAdministrador;
    private javax.swing.JLabel TextCliente;
    private javax.swing.JLabel TextMitad;
    private javax.swing.JLabel TextPregunta;
    private javax.swing.JLabel TextTitulo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
