/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.vehicles;

import com.tecno_comfenalco.easywashproject.controllers.AuthController;
import com.tecno_comfenalco.easywashproject.controllers.VehicleController;
import com.tecno_comfenalco.easywashproject.enums.EnumVehicleType;
import com.tecno_comfenalco.easywashproject.models.Client;
import com.tecno_comfenalco.easywashproject.models.Vehicle;

import javax.swing.JFrame;

import com.tecno_comfenalco.easywashproject.repository.ClientRepository;
import com.tecno_comfenalco.easywashproject.repository.FileBasedRepsitoryImpl.ClientRepositoryImpl;

/**
 *
 * @author jacob
 */
public class RegisterVehicle extends javax.swing.JFrame {

    // Instancia de AuthController para obtener la sesión actual
    private final AuthController authController = AuthController.getInstance();

    /**
     * Creates new form RegisterVehicle1
     */
    public RegisterVehicle() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // No cerrar toda la app
        addRegisterButtonListener();
    }

    private void addRegisterButtonListener() {
        btnRegisterVehicle.addActionListener(e -> onRegisterVehicle());
    }

    private void onRegisterVehicle() {
        try {
            String model = textFieldModel.getText().trim();
            String brand = textFieldBrand.getText().trim();
            String plate = textFieldPlate.getText().trim();
            String color = textFieldColor.getText().trim();
            String typeStr = (String) comboBoxVehicleType.getSelectedItem();

            // Validaciones básicas
            if (model.isEmpty() || brand.isEmpty() || plate.isEmpty() || color.isEmpty() || typeStr == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Convertir tipo de vehículo
            EnumVehicleType type;
            try {
                type = EnumVehicleType.fromDescription(typeStr);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tipo de vehículo no válido.", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            Client client;
            String session = authController.getSession();

            if (session == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay sesión activa.", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            ClientRepositoryImpl clientRepository = new ClientRepositoryImpl();

            client = clientRepository.findByDocumentNumber(session);

            if (client == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Debe iniciar sesión como cliente para registrar un vehículo.", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Registrar el vehículo y asignarlo al cliente autenticado
            Vehicle vehicle = new Vehicle(model, brand, plate, color, type);
            VehicleController controller = new VehicleController();
            controller.createVehicleAndAssignToOwner(vehicle, client.getId());
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar el vehículo: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelTextDescription = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        textFieldModel = new javax.swing.JTextField();
        labelBrand = new javax.swing.JLabel();
        textFieldBrand = new javax.swing.JTextField();
        labelVehicleType = new javax.swing.JLabel();
        comboBoxVehicleType = new javax.swing.JComboBox<>();
        labelPlate = new javax.swing.JLabel();
        textFieldPlate = new javax.swing.JTextField();
        labelColor = new javax.swing.JLabel();
        textFieldColor = new javax.swing.JTextField();
        btnRegisterVehicle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        labelTitle.setText("Registro de Nuevo Vehiculo");
        bg.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        labelTextDescription.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelTextDescription.setText("Los vehiculos registrados se usaran para agilizar el agendamiento de citas.");
        bg.add(labelTextDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        labelModelo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelModelo.setText("Modelo");
        bg.add(labelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        textFieldModel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldModel.setText("Ingrese el modelo de su vehiculo");
        bg.add(textFieldModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 240, 40));

        labelBrand.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelBrand.setText("Marca");
        bg.add(labelBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        textFieldBrand.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldBrand.setText("Ingrese la marca de su vehiculo");
        bg.add(textFieldBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 240, 40));

        labelVehicleType.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelVehicleType.setText("Tipo de Vehiculo");
        bg.add(labelVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        comboBoxVehicleType.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Camioneta", "Moto", "Carro", "Buceta" }));
        bg.add(comboBoxVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 240, 40));

        labelPlate.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelPlate.setText("Placa o Matricula");
        bg.add(labelPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        textFieldPlate.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldPlate.setText("Ingrese su placa");
        bg.add(textFieldPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 240, 40));

        labelColor.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelColor.setText("Color");
        bg.add(labelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        textFieldColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldColor.setText("Ingrese el color de su vehiculo");
        bg.add(textFieldColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 240, 40));

        btnRegisterVehicle.setBackground(new java.awt.Color(153, 153, 153));
        btnRegisterVehicle.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnRegisterVehicle.setText("Registrar");
        btnRegisterVehicle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(btnRegisterVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 180, 40));

        // AGREGA ESTA LÍNEA:
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterVehicle.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterVehicle.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterVehicle.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterVehicle.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegisterVehicle;
    private javax.swing.JTextField textFieldBrand;
    private javax.swing.JComboBox<String> comboBoxVehicleType;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTextDescription;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelBrand;
    private javax.swing.JLabel labelVehicleType;
    private javax.swing.JLabel labelPlate;
    private javax.swing.JLabel labelColor;
    private javax.swing.JTextField textFieldPlate;
    private javax.swing.JTextField textFieldModel;
    private javax.swing.JTextField textFieldColor;
    // End of variables declaration//GEN-END:variables
}
