/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.auth;

import com.tecno_comfenalco.easywashproject.controllers.AuthController;
import com.tecno_comfenalco.easywashproject.views.admin.DashboardUserView;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;

/**
 *
 * @author jacob
 */
public class LoginUserView extends javax.swing.JFrame {

    /**
     * Creates new form LoginUserView1
     */
    public LoginUserView() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textTitulo = new javax.swing.JLabel();
        textitulonombre = new javax.swing.JLabel();
        IngresarUsuario = new javax.swing.JTextField();
        TextContraseña = new javax.swing.JLabel();
        IngresarContraseña = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 759, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        textTitulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        textTitulo.setText("Inicio de Sesion del Usuario");
        bg.add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        textitulonombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        textitulonombre.setText("Nombre de Usuario");
        bg.add(textitulonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        IngresarUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngresarUsuario.setText("Ingrese su nombre de usuario");
        bg.add(IngresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 192, 250, 50));

        TextContraseña.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        TextContraseña.setText("Contraseña");
        bg.add(TextContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        IngresarContraseña.setText("jPasswordField1");
        bg.add(IngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 312, 250, 50));

        loginButton.setBackground(new java.awt.Color(153, 153, 153));
        loginButton.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        loginButton.setText("Ingresar");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        loginButton.addActionListener(e -> loginButtonActionPerformed(e));

        bg.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 383, 180, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/EasyWash_transparente_v2.png"))); // NOI18N
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 460, 290));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/Imagen lavadero.png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 36, 420, 470));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(ActionEvent ev) {
        AuthController authController = new AuthController();
        boolean authentication = authController.authenticateUser(IngresarUsuario.getText(), String.copyValueOf(IngresarContraseña.getPassword()));

        if (authentication) {
            this.setVisible(false);

            new DashboardUserView(authController.getSession()).setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField IngresarContraseña;
    private javax.swing.JTextField IngresarUsuario;
    private javax.swing.JLabel TextContraseña;
    private javax.swing.JPanel bg;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textTitulo;
    private javax.swing.JLabel textitulonombre;
    // End of variables declaration//GEN-END:variables
}
