/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.clients;

import com.tecno_comfenalco.easywashproject.controllers.NavigationManager;
import com.tecno_comfenalco.easywashproject.views.appointments.AgendarCitaPanel;
import com.tecno_comfenalco.easywashproject.views.appointments.VerCitasPanel;
import com.tecno_comfenalco.easywashproject.views.appointments.VerHistorialPanel;
import com.tecno_comfenalco.easywashproject.views.vehicles.VerMisVehiculos;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author jacob
 */
public class DashBoardClientView extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardClientView1
     */
    public DashBoardClientView() {
        initComponents();
        
        VerCitasPanel p1 = new VerCitasPanel();
        p1.setSize(640, 400);
        p1.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p1, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        VerCitas = new javax.swing.JButton();
        VerHistorial = new javax.swing.JButton();
        AgendarCita = new javax.swing.JButton();
        VerVehiculo = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        BarraSuperior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Titulo.setText("¡Bienvenido al Sistema, cliente!");
        bg.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        VerCitas.setBackground(new java.awt.Color(153, 204, 255));
        VerCitas.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerCitas.setText("Ver Citas");
        VerCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCitasActionPerformed(evt);
            }
        });
        bg.add(VerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 110, 40));

        VerHistorial.setBackground(new java.awt.Color(255, 255, 204));
        VerHistorial.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerHistorial.setText("Ver Historial");
        VerHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerHistorialActionPerformed(evt);
            }
        });
        bg.add(VerHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 110, 40));

        AgendarCita.setBackground(new java.awt.Color(102, 255, 102));
        AgendarCita.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        AgendarCita.setText("Agendar Cita");
        AgendarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarCitaActionPerformed(evt);
            }
        });
        bg.add(AgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 110, 40));

        VerVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        VerVehiculo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        VerVehiculo.setText("Ver Vehiculo");
        VerVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerVehiculoActionPerformed(evt);
            }
        });
        bg.add(VerVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 110, 40));

        Salir.setBackground(new java.awt.Color(255, 0, 51));
        Salir.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        bg.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 110, 40));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        bg.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 640, 400));

        BarraSuperior.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void VerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerHistorialActionPerformed
        
        VerHistorialPanel p2 = new VerHistorialPanel();
        p2.setSize(640, 400);
        p2.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p2, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerHistorialActionPerformed
    
    private void VerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCitasActionPerformed
       
        
        VerCitasPanel p1 = new VerCitasPanel();
        p1.setSize(640,400);
        p1.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p1, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerCitasActionPerformed
    
    private void AgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarCitaActionPerformed
        AgendarCitaPanel p3 = new AgendarCitaPanel();
        p3.setSize(640, 400);
        p3.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p3, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_AgendarCitaActionPerformed
    
    private void VerVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerVehiculoActionPerformed
        VerMisVehiculos p3 = new VerMisVehiculos();
        p3.setSize(640, 400);
        p3.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(p3, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_VerVehiculoActionPerformed
    
    
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(
        this,
        "¿Estas seguro que desea salir?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION
        );
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            this.dispose();
            NavigationManager.showMainView();
        }
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarCita;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel Content;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VerCitas;
    private javax.swing.JButton VerHistorial;
    private javax.swing.JButton VerVehiculo;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
    
    public void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}


