/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tecno_comfenalco.easywashproject.views.layouts;

import com.tecno_comfenalco.easywashproject.controllers.NavigationManager;
import javax.swing.JFrame;

/**
 *
 * @author jacob
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal1
     */
    public VistaPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setupListeners();
        setSize(800, 500);
    }

    private void setupListeners() {
        BotonAdministrador.addActionListener(e -> {
            this.dispose();
            NavigationManager.showLoginUserView();
        });

        BotonCliente.addActionListener(e -> {
            this.dispose();
            NavigationManager.showMainView();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TextTitulo = new javax.swing.JLabel();
        TextPregunta = new javax.swing.JLabel();
        BotonCliente = new javax.swing.JButton();
        BotonAdministrador = new javax.swing.JButton();
        TextTitulo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        TextTitulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextTitulo.setText("¡Hola! Bienvenido al Sistema ");
        bg.add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 330, 50));

        TextPregunta.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextPregunta.setText("¿Quien eres?");
        bg.add(TextPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        BotonCliente.setBackground(new java.awt.Color(51, 255, 51));
        BotonCliente.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonCliente.setText("¿Un cliente?");
        BotonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClienteActionPerformed(evt);
            }
        });
        bg.add(BotonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 160, 50));

        BotonAdministrador.setBackground(new java.awt.Color(255, 204, 102));
        BotonAdministrador.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        BotonAdministrador.setText("¿Un Administrador?");
        BotonAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAdministradorActionPerformed(evt);
            }
        });
        bg.add(BotonAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 160, 50));

        TextTitulo2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TextTitulo2.setText("de Gestion de Citas EasyWash");
        bg.add(TextTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/IconCliente (1).png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, 220));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/IconEmpresario (1).png"))); // NOI18N
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/EasyWash_transparente_v2.png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 450, 330));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/EasyWash4 (1).jpg"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 36, 400, 470));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClienteActionPerformed

    }//GEN-LAST:event_BotonClienteActionPerformed

    private void BotonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAdministradorActionPerformed

    }//GEN-LAST:event_BotonAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAdministrador;
    private javax.swing.JButton BotonCliente;
    private javax.swing.JLabel TextPregunta;
    private javax.swing.JLabel TextTitulo;
    private javax.swing.JLabel TextTitulo2;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
